### ISSUE TITLE
Coding Style: Tabs or Spaces

### ISSUE THREAD

**Issue by marcobiedermann** [ro-a-fi/ConFlatao#10]
I suggest to build everything upon one coding style. Do you prefer tabs or spaces and how much do you like to indent them?
I always use two spaces for css because this is the recommendation from Google and SassGuidelines. Yeah, this topic is a debate on it's own but because you are the creator, what do you like more?

Hope this is ok, that I am pushing forward but maybe this theme might end up being in Contao 4.0 :D

**Comment by ro-a-fi** [comment]
​Its a good thing to follow one coding style, so just go on. I didn't know,
Google recommends using two spaces, so I'm certainly okay with two spaces.
I'm really happy and excited about that you continue working on this theme.
In the last month I was so busy studying, that I did not have the time to
work on it.

How come this theme might end up in Contao 4.0? Are there any discussions
about that? This would be awesome.

Beste Grüße,
Raphael

Webdesign & Neue Medien
http://raphael-leuthner.de

2015-04-21 23:16 GMT+02:00 Marco Biedermann <notifications@github.com>:

**Comment by marcobiedermann** [comment]
@ro-a-fi You can merge via GitHub. This way, issues will automatically close it you reference them in your commit message with some keywords like: close, closed, solves, solved, fix, fixed…
See https://help.github.com/articles/closing-issues-via-commit-messages/ for more information :)
