### ISSUE TITLE
Relative Units

### ISSUE THREAD

**Issue by marcobiedermann** [ro-a-fi/ConFlatao#11]
Hey, how do you like relative units? Currently everything is coded in `px`. 
I personally use `rems` since a few months. Before I used `ems` but `rems` work a bit nicer. The benefit of this technique would be that everything builds upon a base size. I suggest using e.g. `14px ~ 0.875rems` and use multiples / divisions for spacing. E.g. `.25rem`, `.5rem`, `.75rem`, `1rem`, `1.5rem`. This will be a more consistent approach and also be very simple to code.
The only downside of `rems` is that it is only supported in `IE9+`. My go would be using `rems` with a fallback of `px` so it is easy to drop `IE8` support in the near future.
Of course this will cause that the theme looks slightly different but I think this is a more consistent way. Also the big benefit of this is that it will scale according to the browser settings. If the user changes the default text size to e.g. `24px` everything will scale up.

**Comment by marcobiedermann** [comment]
@ro-a-fi What is you opinion on this topic?

**Comment by ro-a-fi** [comment]
I'm totally okay with relative Units. Sure the theme will Look
slightly different, but its more Important to be consistent here.

Am Sonntag, 24. Mai 2015 schrieb Marco Biedermann :

> @ro-a-fi <https://github.com/ro-a-fi> What is you opinion on this topic?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ro-a-fi/ConFlatao/issues/11#issuecomment-105017651>.
>


-- 
Beste Grüße,
Raphael

Webdesign & Neue Medien
http://raphael-leuthner.de

**Comment by marcobiedermann** [comment]
@ro-a-fi I am currently working on this one. Also doing some cleanup and refactoring :)
I let you know when I am done.
