### ISSUE TITLE
Ist das Theme noch in Bearbeitung?

### ISSUE THREAD

**Issue by leofeyer** [ro-a-fi/ConFlatao#2]
Hallo Raphael, wie weit ist denn Dein Theme inzwischen? Ist es noch in Bearbeitung oder schon fertig?

**Comment by ro-a-fi** [comment]
Hallo Leo,

danke für die Nachricht. Durch mein Studium konnte ich für einige Zeit
leider nicht aktiv daran weiterarbeiten.
Wenn aber Interesse an der Entwicklung besteht, würde ich mich demnächst
weiter mit dem Theme beschäftigen.

Beste Grüße,
Raphael

Webdesign & Neue Medien
http://raphael-leuthner.de

Am 15. April 2015 um 12:28 schrieb Leo Feyer <notifications@github.com>:

**Comment by GodMod** [comment]
Nachdem der letzte Commit leider schon etwas her ist, schließ ich mich der Frage von Leo an... Ich find dein BE Theme super, und würde mich deshalb freuen, wenn die Entwicklungs weitergehen würde.

**Comment by ro-a-fi** [comment]
Vielen Danke für das Feedback! Ich selber habe aktuell leider nur wenig
Zeit. An der Weiterentwicklung darf sich natürlich jeder gerne beteiligen.
marcobiedermann <https://github.com/marcobiedermann> z.B. hat sich hier
schon viel miteingebracht und einiges geleistet.
