### ISSUE TITLE
Sass Support

### ISSUE THREAD

**Issue by marcobiedermann** [ro-a-fi/ConFlatao#3]
Hey Raphael,

I really like this theme and would help you with it, if you want to.
My suggestion is to code it in Scss instead of regular CSS, so we can take advantage of variables for spacing and colors, functions and loops. This way, everything is more dynamic and consistent.
If you agree, I can take care of this and send you a PR :)

**Comment by ro-a-fi** [comment]
Hi Marco,

I'm glad to hear that you like the theme and it would be great to get some
help!
Your suggestions sound good.

I'm excited about your ideas and how the theme develops.

​Kind regards
,
Raphael

Webdesign & Neue Medien
http://raphael-leuthner.de

2015-04-21 14:23 GMT+02:00 Marco Biedermann <notifications@github.com>:

**Comment by marcobiedermann** [comment]
Yeah, cool. I work with Contao every day and to be honest, I do not like the default BE that much.
I am going to make some proposals for this theme and help fixing suff and making it more robust / stable. If you got any questions or just want to chat, you can ping me via [Twitter](http://twitter.com/m412c0b) or on Skype :)

**Comment by marcobiedermann** [comment]
This is currently in progress. @ro-a-fi Could you please add a label called "in progress", so I can mark think if I am working on them?!

**Comment by marcobiedermann** [comment]
ToDo:
* [ ] Selector Nesting
* [ ] Settings Variables and Colors
* [ ] Mixins
